---



- name: Role agp_devspaces | Task workload | Install DevWorkspace Operator
  ansible.builtin.include_tasks: ./install_operator.yml
  vars:
    install_operator_action: install
    install_operator_name: "{{ agp_devspaces_operator_devworkspace_name }}"
    install_operator_namespace: "{{ agp_devspaces_operator_devworkspace_namespace }}"
    install_operator_catalog: "{{ agp_devspaces_operator_catalog_name }}"
    install_operator_channel: "{{ agp_devspaces_operator_devworkspace_channel }}"
    install_operator_automatic_install_plan_approval: "{{ agp_devspaces_operator_devworkspace_install_plan_automatic | default(true) }}" # yamllint disable-line rule:line-length
    install_operator_starting_csv: "{{ agp_devspaces_operator_devworkspace_starting_csv }}"
    install_operator_packagemanifest_name: "{{ agp_devspaces_operator_devworkspace_operator_name }}"
    # install_operator_manage_namespaces:
    #   - "{{ agp_devspaces_namespace }}"
    install_operator_catalogsource_setup: "{{ agp_devspaces_operator_catalog_create }}"
    install_operator_catalogsource_name: "{{ agp_devspaces_operator_catalog_name | default('') }}"
    install_operator_catalogsource_image: "{{ agp_devspaces_operator_catalog_image | default('') }}"
    install_operator_catalogsource_image_tag: "{{ agp_devspaces_operator_catalog_image_tag | default('') }}"
    install_operator_catalogsource_namespace: "{{ agp_devspaces_operator_catalog_namespace }}"
    install_operator_csv_nameprefix: "{{ agp_devspaces_operator_devworkspace_operator_name }}"
    install_operator_install_csv_ignore_error: false
    install_operator_catalogsource_pullsecrets: []

# TODO - better install process
- name: Role agp_devspaces | Task workload | Install DevSpaces Operator
  ansible.builtin.include_tasks: ./install_operator.yml
  vars:
    install_operator_action: install
    install_operator_name: "{{ agp_devspaces_operator_devspaces_name }}"
    install_operator_namespace: "{{ agp_devspaces_namespace }}"
    install_operator_catalog: "{{ agp_devspaces_operator_catalog_name }}"
    install_operator_channel: "{{ agp_devspaces_operator_devspaces_channel }}"
    install_operator_automatic_install_plan_approval: "{{ agp_devspaces_operator_devspaces_install_plan_automatic | default(true) }}" # yamllint disable-line rule:line-length
    install_operator_starting_csv: "{{ agp_devspaces_operator_devspaces_starting_csv }}"
    install_operator_packagemanifest_name: "{{ agp_devspaces_operator_devspaces_operator_name }}"
    # install_operator_manage_namespaces:
    #   - "{{ agp_devspaces_namespace }}"
    install_operator_catalogsource_setup: "{{ agp_devspaces_operator_catalog_create }}"
    install_operator_catalogsource_name: "{{ agp_devspaces_operator_catalog_name | default('') }}"
    install_operator_catalogsource_image: "{{ agp_devspaces_operator_catalog_image | default('') }}"
    install_operator_catalogsource_image_tag: "{{ agp_devspaces_operator_catalog_image_tag | default('') }}"
    install_operator_catalogsource_namespace: "{{ agp_devspaces_operator_catalog_namespace }}"
    install_operator_csv_nameprefix: "{{ agp_devspaces_operator_devspaces_operator_name }}"
    install_operator_install_csv_ignore_error: false
    install_operator_catalogsource_pullsecrets: []

# - name: Role agp_devspaces | Task workload | Create Devspaces OperatorGroup
#   when: agp_devspaces_operator_group_create
#   kubernetes.core.k8s:
#     state: "{{ agp_devspaces_state }}"
#     definition:
#       apiVersion: operators.coreos.com/v1
#       kind: OperatorGroup
#       metadata:
#         name: "{{ agp_devspaces_operator_group_name }}"
#         namespace: "{{ agp_devspaces_operator_devspaces_namespace }}"
#       spec: "{{ agp_devspaces_operator_group_spec }}"

- name: Role agp_devspaces | Task workload | Create custom SCC nested-podman-scc
  kubernetes.core.k8s:
    state: "{{ agp_devspaces_state }}"
    definition: "{{ agp_devspaces_custom_nested_podman_scc }}"

# - name: Role agp_devspaces | Task workload | Install OCP Devworkspace Operator
#   kubernetes.core.k8s:
#     state: "{{ agp_devspaces_state }}"
#     definition:
#       apiVersion: operators.coreos.com/v1alpha1
#       kind: Subscription
#       metadata:
#         name: "{{ agp_devspaces_operator_devworkspace_name }}"
#         namespace: "{{ agp_devspaces_operator_devworkspace_namespace }}"
#         labels: "{{ agp_devspaces_operator_devworkspace_labels }}"
#       spec:
#         channel: "{{ agp_devspaces_operator_devworkspace_channel }}"
#         installPlanApproval: "{{ agp_devspaces_operator_devworkspace_install_plan }}"
#         name: "{{ agp_devspaces_operator_devworkspace_operator_name }}"
#         source: "{{ agp_devspaces_operator_devworkspace_source }}"
#         sourceNamespace: "{{ agp_devspaces_operator_devworkspace_source_namespace }}"
#         startingCSV: "{{ agp_devspaces_operator_devworkspace_starting_csv }}"

# - name: Role agp_devspaces | Task workload | Install OCP DevSpaces Subscription
#   kubernetes.core.k8s:
#     state: "{{ agp_devspaces_state }}"
#     definition:
#       apiVersion: operators.coreos.com/v1alpha1
#       kind: Subscription
#       metadata:
#         name: "{{ agp_devspaces_operator_devspaces_name }}"
#         namespace: "{{ agp_devspaces_operator_devspaces_namespace }}"
#         labels: "{{ agp_devspaces_operator_devspaces_labels }}"
#       spec:
#         channel: "{{ agp_devspaces_operator_devspaces_channel }}"
#         installPlanApproval: "{{ agp_devspaces_operator_devspaces_install_plan_automatic }}"
#         name: "{{ agp_devspaces_operator_devspaces_operator_name }}"
#         source: "{{ agp_devspaces_operator_devspaces_source }}"
#         sourceNamespace: "{{ agp_devspaces_operator_devspaces_source_namespace }}"
#         startingCSV: "{{ agp_devspaces_operator_devspaces_starting_csv }}"

# - name: Role agp_devspaces | Task workload | Pause for 5 minutes to allow Operators to install
#   ansible.builtin.pause:
#     minutes: 5

- name: Role agp_devspaces | Task workload | Install CheCluster
  block:

    - name: Role agp_devspaces | Task workload | Create CheCluster
      kubernetes.core.k8s:
        state: "{{ agp_devspaces_state }}"
        definition:
          apiVersion: org.eclipse.che/v2
          kind: CheCluster
          metadata:
            name: devspaces
            namespace: "{{ agp_devspaces_namespace }}"
          spec: "{{ agp_devspaces_che_cluster_spec }}"
      retries: 30
      delay: 30

  rescue:

    - name: Role agp_devspaces | Task workload | Pause for 5 additional minutes to allow Operators to install
      ansible.builtin.pause:
        minutes: 5

    - name: Role agp_devspaces | Task workload | Create CheCluster
      kubernetes.core.k8s:
        state: "{{ agp_devspaces_state }}"
        definition:
          apiVersion: org.eclipse.che/v2
          kind: CheCluster
          metadata:
            name: devspaces
            namespace: "{{ agp_devspaces_namespace }}"
          spec: "{{ agp_devspaces_che_cluster_spec }}"
      retries: 30
      delay: 30

- name: Role agp_devspaces | task workload | Deploy default workspace configurations
  when: agp_devspaces_default_workspace_config
  kubernetes.core.k8s:
    state: "{{ agp_devspaces_state }}"
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: vscode-editor-configurations
        namespace: "{{ agp_devspaces_namespace }}"
        labels:
          app.kubernetes.io/part-of: che.eclipse.org
          app.kubernetes.io/component: workspaces-config
      data:
        extensions.json: "{{ agp_devspaces_default_workspace_extensions_json | string }}"
        settings.json: "{{ agp_devspaces_default_workspace_settings_json | string }}"
        configurations.json: "{{ agp_devspaces_default_workspace_configurations_json | string }}"
