---
# Implement your Pre Workload deployment tasks here
# -------------------------------------------------


# Leave these as the last tasks in the playbook
# ---------------------------------------------

# For deployment onto a dedicated cluster (as part of the
# cluster deployment) set workload_shared_deployment to False
# This is the default so it does not have to be set explicitely
- name: Role agp_featuregate | Task pre_workload | pre_workload tasks complete
  ansible.builtin.debug:
    msg: "Pre-Workload tasks completed successfully."
  when:
    - not agp_featuregate_silent | bool
    - not workload_shared_deployment | default(false) | bool

# For RHPDS deployment (onto a shared cluster) set
# workload_shared_deployment to True
# (in the deploy script or AgnosticV configuration)
- name: Role agp_featuregate | Task pre_workload | pre_workload tasks complete
  ansible.builtin.debug:
    msg: "Pre-Software checks completed successfully"
  when:
    - not agp_featuregate_silent | bool
    - workload_shared_deployment | default(false) | bool
